### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by jephthai** [xdsopl/qsstv#2]
I experience random crashes while using QSSTV, and have been unsuccessful figuring out what causes it.  I thought maybe I had an old version from the Ubuntu repo or something, but when I went to compile QSSTV from scratch, I noticed no significant difference.  That made me think maybe my system was unstable somehow, but when I tried it on a Raspberry Pi with a current stock distribution and had the same issues, it made me wonder.

Is there a known cause for the random crashes?  Sometimes QSSTV will run for an hour; sometimes for less than a minute.  I haven't been able to correlated with any specific activity.  It's just a hard crash, window disappears, and I'm back to the controlling terminal.  

It really affects QSSTV's usability, as I have to babysit it and restart it frequently.  This behavior also makes me very unlikely to use it for TX, because I can't seem to trust it.

Any help understanding or diagnosing the crashes would be appreciated -- or even just confirmation that I'm not alone, and that this is a known problem and it's being investigated would be nice.

**Comment by xdsopl** [comment]
I've never let QSSTV run longer than an hour and can't really recall that it crashed even once on me.
If you want to find out where it crashes, compile it with debug symbols enabled and run it in a debugger like lldb or gdb until it crashes and hopefully the debugger will reveal the problem or at least the symptoms.
If you need help with that, please don't hesitate to ask.

**Comment by jephthai** [comment]
OK, I've compiled a debug build, and will monitor and see if I can produce something tangible.  I guess since this is a nebulous report, I'll close it, and just open a more specific issue if I narrow down what's causing the crashes on my system.  Thanks!
