### ISSUE TITLE
Feature request(s) - Picturesize in digital and "chat" functionality

### ISSUE THREAD

**Issue by ploeffler** [xdsopl/qsstv#3]
after writing an email to ON4QZ several weeks ago without any answer, I thought of placing some ideas here:

*) in the digital-tx-tab there is a slider at the bottom named "image-size". thats a bit misleading, because (without checking the sourcecode) it seems to effects the jpg-compression-level (filesize) and NOT the imagesize. so (maybe) a second slider to change the imagesize (keeping aspect-ratio) would be a extra-good idea.

*) the problem with dual transmissions (as we can see on 14.230 e.g.) could either be solved by brainwashing some users (hi) or by implementing some (automated)feedback and chat functionality using APRS and/or pskreporter. in http://aprs.org/aprs11/tocalls.txt the segment APDVxx is already preserved for that purpose. 

regards
peter (OE6PLD)

**Comment by xdsopl** [comment]
As always, patches are very welcome!
