### ISSUE TITLE
Feature request - Add AppStream metadata

### ISSUE THREAD

**Issue by AsciiWolf** [xdsopl/qsstv#4]
Consider adding [AppStream](https://www.freedesktop.org/wiki/Distributions/AppStream/) metadata file for QSSTV to make it searchable and installable using AppStream-based Linux package managers like GNOME Software or KDE Discover.

**Comment by xdsopl** [comment]
Great idea! Can you write a patch for it?

**Comment by AsciiWolf** [comment]
Here is a quick AppStream metadata file that I made:

```
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
 <id>qsstv.desktop</id>
 <metadata_license>CC0-1.0</metadata_license>
 <project_license>GPL-3.0</project_license>
 <name>QSSTV</name>
 <summary>Program for receiving and transmitting SSTV and HAMDRM</summary>
 <description>
  <p>QSSTV is a program for receiving and transmitting SSTV and HAMDRM (sometimes called DSSTV). It is compatible with most of MMSSTV and EasyPal.</p>
 </description>
 <screenshots>
  <screenshot type="default">
   <image>http://users.telenet.be/on4qz/qsstv/manual/rxwidget1.png</image>
   <caption>Receive SSTV Window</caption>
  </screenshot>
 </screenshots>
 <url type="homepage">http://users.telenet.be/on4qz</url>
 <content_rating type="oars-1.1"/>
</component>
```

It needs to be placed to the [qsstv](https://github.com/xdsopl/qsstv/tree/master/qsstv) directory as `qsstv.appdata.xml` and added to [qsstv.pro](https://github.com/xdsopl/qsstv/blob/master/qsstv/qsstv.pro) (to install it into `/usr/share/metainfo`). I am unfortunately not so skilled with qmake to do it myself, but you are feel free to use the AppStream file however you like. :-)

**Comment by xdsopl** [comment]
Also not skilled with qmake but we ain't come this far to just give up. :)
Please fork this project, add the changes you mentioned to your fork and send a pull request.
Don't be afraid to make mistakes, I am here to help. ;-)

**Comment by AsciiWolf** [comment]
@xdsopl Done in #5.
